/**
 * lib/sources.js
 * All Pakistan-focused news sources.
 * Rules: No Indian media, no Israeli media.
 * International coverage of Pakistan (BBC Urdu, Al Jazeera Pakistan) is included.
 */

const SOURCES = [
  // ── English Print ──────────────────────────────────────────────────
  {
    id:    'dawn',
    name:  'Dawn',
    url:   'https://www.dawn.com/feeds/latest-news',
    color: '#006B3C',
    type:  'English',
    lang:  'en',
  },
  {
    id:    'thenews',
    name:  'The News',
    url:   'https://www.thenews.com.pk/rss/1/16',
    color: '#1B4F72',
    type:  'English',
    lang:  'en',
  },
  {
    id:    'tribune',
    name:  'Express Tribune',
    url:   'https://tribune.com.pk/feed/pakistan',
    color: '#C0392B',
    type:  'English',
    lang:  'en',
  },
  {
    id:    'brecorder',
    name:  'Business Recorder',
    url:   'https://www.brecorder.com/feed/',
    color: '#1E8449',
    type:  'Business',
    lang:  'en',
  },
  {
    id:    'propakistani',
    name:  'ProPakistani',
    url:   'https://propakistani.pk/feed/',
    color: '#E67E22',
    type:  'Digital',
    lang:  'en',
  },
  {
    id:    'profit',
    name:  'Profit',
    url:   'https://profit.pakistantoday.com.pk/feed/',
    color: '#2C3E50',
    type:  'Business',
    lang:  'en',
  },
  {
    id:    'techjuice',
    name:  'TechJuice',
    url:   'https://www.techjuice.pk/feed/',
    color: '#8E44AD',
    type:  'Tech',
    lang:  'en',
  },
  {
    id:    'geo',
    name:  'Geo News',
    url:   'https://www.geo.tv/rss/1',
    color: '#00843D',
    type:  'TV',
    lang:  'en',
  },
  {
    id:    'ary',
    name:  'ARY News',
    url:   'https://arynews.tv/feed',
    color: '#00529B',
    type:  'TV',
    lang:  'en',
  },
  {
    id:    'samaa',
    name:  'Samaa TV',
    url:   'https://www.samaa.tv/feed/',
    color: '#E07B1A',
    type:  'TV',
    lang:  'en',
  },
  {
    id:    'dunya',
    name:  'Dunya News',
    url:   'https://dunyanews.tv/index.php/en?format=feed&type=rss',
    color: '#A93226',
    type:  'TV',
    lang:  'en',
  },
  {
    id:    'paktoday',
    name:  'Pakistan Today',
    url:   'https://www.pakistantoday.com.pk/feed/',
    color: '#1A252F',
    type:  'English',
    lang:  'en',
  },
  {
    id:    'nation',
    name:  'The Nation',
    url:   'https://nation.com.pk/feed/',
    color: '#1A237E',
    type:  'English',
    lang:  'en',
  },
  {
    id:    'nayadaur',
    name:  'Naya Daur',
    url:   'https://nayadaur.tv/feed/',
    color: '#6C3483',
    type:  'Digital',
    lang:  'en',
  },
  {
    id:    'gvs',
    name:  'Global Village Space',
    url:   'https://www.globalvillagespace.com/feed/',
    color: '#16A085',
    type:  'Digital',
    lang:  'en',
  },
  {
    id:    'fridaytimes',
    name:  'The Friday Times',
    url:   'https://thefridaytimes.com/feed/',
    color: '#7F8C8D',
    type:  'Digital',
    lang:  'en',
  },
  // ── Urdu Sources ───────────────────────────────────────────────
  {
    id:    'bbcurdu',
    name:  'BBC Urdu',
    url:   'https://feeds.bbci.co.uk/urdu/rss.xml',
    color: '#BB1919',
    type:  'Urdu',
    lang:  'ur',
  },
  {
    id:    'independenturdu',
    name:  'Independent Urdu',
    url:   'https://www.independenturdu.com/rss',
    color: '#C0392B',
    type:  'Urdu',
    lang:  'ur',
  },
  {
    id:    'voaurdu',
    name:  'VOA Urdu',
    url:   'https://www.urduvoa.com/api/z$gpet-vy_',
    color: '#003366',
    type:  'Urdu',
    lang:  'ur',
  },
  {
    id:    'dawnurdu',
    name:  'Dawn Urdu',
    url:   'https://www.dawnnews.tv/feeds/latest-news',
    color: '#006B3C',
    type:  'Urdu',
    lang:  'ur',
  },
  {
    id:    'aryurdu',
    name:  'ARY News Urdu',
    url:   'https://urdu.arynews.tv/feed/',
    color: '#00529B',
    type:  'Urdu',
    lang:  'ur',
  },
  {
    id:    'geourdu',
    name:  'Geo News Urdu',
    url:   'https://urdu.geo.tv/rss/1/5',
    color: '#00843D',
    type:  'Urdu',
    lang:  'ur',
  },
  {
    id:    'jang',
    name:  'Daily Jang',
    url:   'https://jang.com.pk/rss/1/1',
    color: '#1B4F72',
    type:  'Urdu',
    lang:  'ur',
  },
  {
    id:    'expressurdu',
    name:  'Express News',
    url:   'https://www.express.pk/feed/',
    color: '#C0392B',
    type:  'Urdu',
    lang:  'ur',
  },
  {
    id:    'urdupoint',
    name:  'UrduPoint',
    url:   'https://www.urdupoint.com/pakistan/rss/latest-news.xml',
    color: '#D35400',
    type:  'Urdu',
    lang:  'ur',
  },
  {
    id:    'hamariweb',
    name:  'HamariWeb',
    url:   'https://hamariweb.com/news/rss.aspx',
    color: '#27AE60',
    type:  'Urdu',
    lang:  'ur',
  },
];

module.exports = SOURCES;
