/**
 * lib/sources.js
 * All Pakistan-focused news sources for brief.pk newsfeed.
 *
 * Rules:
 *  - No Indian media, no Israeli media
 *  - pakistanFilter: false  → source is exclusively Pakistan-focused; skip keyword filter
 *  - pakistanFilter: true   → international/mixed feed; filter by Pakistan keywords
 *  - (no flag)              → treated as true — filtered by default
 *  - lang: 'en' | 'ur'
 *  - type: label shown in sidebar chips
 */

const SOURCES = [

  // ══════════════════════════════════════════════════════════════════
  // ENGLISH — PRINT & DIGITAL
  // ══════════════════════════════════════════════════════════════════
  {
    id:             'dawn',
    name:           'Dawn',
    url:            'https://www.dawn.com/feeds/latest-news',
    color:          '#006B3C',
    type:           'Print',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'thenews',
    name:           'The News',
    url:            'https://www.thenews.com.pk/rss/1/16',
    color:          '#1B4F72',
    type:           'Print',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'tribune',
    name:           'Express Tribune',
    url:            'https://tribune.com.pk/feed/pakistan',
    color:          '#C0392B',
    type:           'Print',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'paktoday',
    name:           'Pakistan Today',
    url:            'https://www.pakistantoday.com.pk/feed/',
    color:          '#1A252F',
    type:           'Print',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'nation',
    name:           'The Nation',
    url:            'https://nation.com.pk/feed/',
    color:          '#1A237E',
    type:           'Print',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'dailytimes',
    name:           'Daily Times',
    url:            'https://dailytimes.com.pk/feed/',
    color:          '#B7410E',
    type:           'Print',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'pakobserver',
    name:           'Pakistan Observer',
    url:            'https://pakobserver.net/feed/',
    color:          '#2E4053',
    type:           'Print',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'minutemirror',
    name:           'Minute Mirror',
    url:            'https://minutemirror.com.pk/feed/',
    color:          '#1565C0',
    type:           'Digital',
    lang:           'en',
    pakistanFilter: true, // publishes Bollywood/entertainment and international content
  },
  {
    id:             'nayadaur',
    name:           'Naya Daur',
    url:            'https://nayadaur.tv/feed/',
    color:          '#6C3483',
    type:           'Digital',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'gvs',
    name:           'Global Village Space',
    url:            'https://www.globalvillagespace.com/feed/',
    color:          '#16A085',
    type:           'Digital',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'fridaytimes',
    name:           'The Friday Times',
    url:            'https://thefridaytimes.com/feed/',
    color:          '#7F8C8D',
    type:           'Digital',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'pakistanpoint',
    name:           'Pakistan Point',
    url:            'https://www.pakistanpoint.net/english/rss/latestNews.xml',
    color:          '#00695C',
    type:           'Digital',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'geonews',
    name:           'Geo News',
    url:            'https://www.geo.tv/rss/1',
    color:          '#00843D',
    type:           'TV',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'arynews',
    name:           'ARY News',
    url:            'https://arynews.tv/feed',
    color:          '#00529B',
    type:           'TV',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'samaa',
    name:           'Samaa TV',
    url:            'https://www.samaa.tv/feed/',
    color:          '#E07B1A',
    type:           'TV',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'dunya',
    name:           'Dunya News',
    url:            'https://dunyanews.tv/index.php/en?format=feed&type=rss',
    color:          '#A93226',
    type:           'TV',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'bolnews',
    name:           'BOL News',
    url:            'https://www.bolnews.com/feed/',
    color:          '#E74C3C',
    type:           'TV',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             '92news',
    name:           '92 News',
    url:            'https://92newshd.tv/feed/',
    color:          '#922B21',
    type:           'TV',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'humnews',
    name:           'Hum News',
    url:            'https://humnews.pk/feed/',
    color:          '#D35400',
    type:           'TV',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'channelfire',
    name:           'Channel 24',
    url:            'https://www.channel24.pk/feed/',
    color:          '#1F618D',
    type:           'TV',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'abbtak',
    name:           'Abb Takk',
    url:            'https://www.abbtakk.tv/feed/',
    color:          '#154360',
    type:           'TV',
    lang:           'en',
    pakistanFilter: false,
  },

  // ══════════════════════════════════════════════════════════════════
  // BUSINESS & ECONOMY
  // ══════════════════════════════════════════════════════════════════
  {
    id:             'brecorder-latest',
    name:           'Business Recorder',
    url:            'https://www.brecorder.com/feed/',
    color:          '#1E8449',
    type:           'Business',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'brecorder-markets',
    name:           'BR Markets',
    url:            'https://www.brecorder.com/rss/markets/',
    color:          '#1E8449',
    type:           'Business',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'brecorder-pakistan',
    name:           'BR Pakistan',
    url:            'https://www.brecorder.com/rss/pakistan/',
    color:          '#1E8449',
    type:           'Business',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'profit',
    name:           'Profit by Pakistan Today',
    url:            'https://profit.pakistantoday.com.pk/feed/',
    color:          '#2C3E50',
    type:           'Business',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'thenewsmoney',
    name:           'The News — Money',
    url:            'https://www.thenews.com.pk/rss/3/5',
    color:          '#1B4F72',
    type:           'Business',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'mettis',
    name:           'Mettis Global',
    url:            'https://mettisglobal.news/feed/',
    color:          '#004A99',
    type:           'Business',
    lang:           'en',
    pakistanFilter: false,
  },

  // ══════════════════════════════════════════════════════════════════
  // TECH & DIGITAL
  // ══════════════════════════════════════════════════════════════════
  {
    id:             'propakistani',
    name:           'ProPakistani',
    url:            'https://propakistani.pk/feed/',
    color:          '#E67E22',
    type:           'Tech',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'techjuice',
    name:           'TechJuice',
    url:            'https://www.techjuice.pk/feed/',
    color:          '#8E44AD',
    type:           'Tech',
    lang:           'en',
    pakistanFilter: false,
  },

  // ══════════════════════════════════════════════════════════════════
  // INTERNATIONAL — Pakistan keyword filter applied
  // ══════════════════════════════════════════════════════════════════
  {
    id:             'aljazeera',
    name:           'Al Jazeera',
    url:            'https://www.aljazeera.com/xml/rss/all.xml',
    color:          '#FF6B35',
    type:           'International',
    lang:           'en',
    pakistanFilter: true,
  },
  {
    id:             'reutersworld',
    name:           'Reuters',
    url:            'https://feeds.reuters.com/reuters/worldNews',
    color:          '#E53935',
    type:           'International',
    lang:           'en',
    pakistanFilter: true,
  },
  {
    id:             'apnews',
    name:           'AP News',
    url:            'https://rsshub.app/apnews/topics/pakistan',
    color:          '#BF360C',
    type:           'International',
    lang:           'en',
    pakistanFilter: true,
  },
  {
    id:             'guardian',
    name:           'The Guardian',
    url:            'https://www.theguardian.com/world/pakistan/rss',
    color:          '#005689',
    type:           'International',
    lang:           'en',
    pakistanFilter: false, // Guardian PK section is already Pakistan-only
  },
  {
    id:             'scmp',
    name:           'South China Morning Post',
    url:            'https://www.scmp.com/rss/91/feed',
    color:          '#C0272D',
    type:           'International',
    lang:           'en',
    pakistanFilter: true,
  },

  // ══════════════════════════════════════════════════════════════════
  // URDU — DOMESTIC (Pakistan-only feeds)
  // ══════════════════════════════════════════════════════════════════
  {
    id:             'dawnurdu',
    name:           'Dawn News اردو',
    url:            'https://www.dawnnews.tv/feeds/latest-news',
    color:          '#006B3C',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'aryurdu',
    name:           'ARY اردو',
    url:            'https://urdu.arynews.tv/feed/',
    color:          '#00529B',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'geourdu',
    name:           'Geo اردو',
    url:            'https://urdu.geo.tv/rss/1/5',
    color:          '#00843D',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'jang',
    name:           'Daily Jang',
    url:            'https://jang.com.pk/rss/1/1',
    color:          '#1B4F72',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'expressurdu',
    name:           'Express News',
    url:            'https://www.express.pk/feed/',
    color:          '#C0392B',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'nawaiwaqt',
    name:           'Nawa-i-Waqt',
    url:            'https://www.nawaiwaqt.com.pk/rss/latest-news',
    color:          '#1A5276',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'ummat',
    name:           'Daily Ummat',
    url:            'https://www.ummat.net/feed/',
    color:          '#117A65',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'ausaf',
    name:           'Daily Ausaf',
    url:            'https://www.ausaf.com.pk/feeds/latest',
    color:          '#1F618D',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'urdupoint',
    name:           'UrduPoint',
    url:            'https://www.urdupoint.com/pakistan/rss/latest-news.xml',
    color:          '#D35400',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'hamariweb',
    name:           'HamariWeb',
    url:            'https://hamariweb.com/news/rss.aspx',
    color:          '#27AE60',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'samaaurdu',
    name:           'Samaa اردو',
    url:            'https://www.samaa.tv/urdu/feed/',
    color:          '#E07B1A',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'bolurdu',
    name:           'BOL اردو',
    url:            'https://www.bolnews.com/urdu/feed/',
    color:          '#E74C3C',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'mashriq',
    name:           'Daily Mashriq',
    url:            'https://www.mashriqtv.pk/feed/',
    color:          '#7D6608',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },
  {
    id:             'brecorderurdu',
    name:           'Business Recorder اردو',
    url:            'https://www.brecorder.com/urdu/feed/',
    color:          '#1E8449',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: false,
  },

  // ══════════════════════════════════════════════════════════════════
  // URDU — INTERNATIONAL (global Urdu services; filter for Pakistan)
  // ══════════════════════════════════════════════════════════════════
  {
    id:             'bbcurdu',
    name:           'BBC اردو',
    url:            'https://feeds.bbci.co.uk/urdu/rss.xml',
    color:          '#BB1919',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: true,
  },
  {
    id:             'voaurdu',
    name:           'VOA اردو',
    url:            'https://www.urduvoa.com/api/z$gpet-vy_',
    color:          '#003366',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: true,
  },
  {
    id:             'independenturdu',
    name:           'Independent اردو',
    url:            'https://www.independenturdu.com/rss',
    color:          '#C0392B',
    type:           'Urdu',
    lang:           'ur',
    pakistanFilter: true,
  },

  // ══════════════════════════════════════════════════════════════════
  // CONFLICT & SECURITY — Border & Regional Watch
  // ══════════════════════════════════════════════════════════════════
  {
    id:             'khorasandiary',
    name:           'The Khorasan Diary',
    url:            'https://thekhorasandiary.com/feed/',
    color:          '#0D0D0D',
    type:           'Conflict',
    lang:           'en',
    pakistanFilter: false, // Af-Pak security focus; all content is relevant
  },
  {
    id:             'crss',
    name:           'CRSS Pakistan',
    url:            'https://crss.pk/feed/',
    color:          '#2E4053',
    type:           'Conflict',
    lang:           'en',
    pakistanFilter: false,
  },
  {
    id:             'tolonews',
    name:           'TOLOnews',
    url:            'https://tolonews.com/afghanistan/rss',
    color:          '#D4AF37',
    type:           'International',
    lang:           'en',
    pakistanFilter: true, // Afghan source — filter for Pakistan-relevant stories
  },
  {
    id:             'khaama',
    name:           'Khaama Press',
    url:            'https://www.khaama.com/feed/',
    color:          '#273746',
    type:           'Conflict',
    lang:           'en',
    pakistanFilter: true,
  },
  {
    id:             'pajhwok',
    name:           'Pajhwok Afghan News',
    url:            'https://pajhwok.com/feed',
    color:          '#A93226',
    type:           'Conflict',
    lang:           'en',
    pakistanFilter: true,
  },
  {
    id:             'gandhara',
    name:           'Gandhara RFA',
    url:            'https://gandhara.rfa.org/rss/all.xml',
    color:          '#E67E22',
    type:           'International',
    lang:           'en',
    pakistanFilter: true,
  },
];

module.exports = SOURCES;
